namespace Xuanwen.Novel
{
	[default_interface]
	runtimeclass Chapter
	{
		Chapter();
		Chapter(UInt32 index, String text);
		UInt32 Index { get; }; 
		String Title { get; }; 
		String Text{ get; };
	}
}
