namespace Xuanwen.Novel
{
	[default_interface]
	runtimeclass Chapter
	{
		Chapter();
		Chapter(UInt32 index, String title, String text);
		UInt32 Index {get; set;}; 
		String Title {get; set;}; 
		String Text{ get; set; };
	}
}
