import "Chapter.idl"; 


namespace Xuanwen.Novel
{
	[default_interface]
	runtimeclass NovelBook
	{
		NovelBook(String filePath);
		
		Windows.Foundation.IAsyncAction InitializeAsync(); 

		String Name{ get; };
		String FilePath{ get; }; 
		UInt32 TotalChars{ get; };
		Windows.Foundation.Collections.IVector<Chapter> Chapters{ get; };
	}
}