import "Delegates.idl"; 
import "MainWindowViewModel.idl"; 

namespace Win2dTextReader
{
    [default_interface]
    runtimeclass BookContents : Microsoft.UI.Xaml.Controls.UserControl
    {
        BookContents(MainWindowViewModel viewModel);
        MainWindowViewModel ViewModel{ get; };
    }
}
