import "FontItem.idl"; 
import "DoubleItem.idl"; 
import "ReaderTheme.idl";

namespace Win2dTextReader
{
	[default_interface]
	runtimeclass MainWindowViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		MainWindowViewModel(); 
		
		void LoadData(); 
		void SaveData();
		void OnChaptersChanged(Object obj); 

		Int32 ChapterIndex; 
		Int32 LineHeightIndex;
		Int32 FontSizeIndex;
		Int32 FontFamilyIndex;
		Int32 ThemeIndex; 

		Int32 WindowPositionX; 
		Int32 WindowPositionY; 
		Int32 WindowSizeW; 
		Int32 WindowSizeH; 
		Double ReaderVerticalOffset; 

		Xuanwen.Novel.NovelBook CurrentBook; 
		Xuanwen.Novel.Chapter CurrentChapter{ get; }; 

		Double LineHeight{ get; }; 
		Double FontSize{ get; }; 
		Microsoft.UI.Xaml.Media.FontFamily FontFamily{ get; }; 
		ReaderTheme AppTheme{ get; }; 

		Windows.Foundation.Collections.IVector<FontItem> FontItems { get; }; 
		Windows.Foundation.Collections.IVector<DoubleItem> FontSizeItems{ get; }; 
		Windows.Foundation.Collections.IVector<DoubleItem> LineHeightItems{ get; };
		Windows.Foundation.Collections.IVector<ReaderTheme> ThemeItems{ get; };
	}
}
