import "Delegates.idl"; 
import "MainWindowViewModel.idl";

namespace Win2dTextReader
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainWindowViewModel ViewModel{ get; }; 

        event ObjectAction ChaptersChanged; 
    }
}
