import "Settings.idl"; 

namespace Win2dTextReader
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Settings ReaderSettings{ get; };
    }
}
