import "DoubleItem.idl"; 
import "AppTheme.idl"; 
import "AppFont.idl"; 
import "FontWeightItem.idl"; 

namespace Win2dTextReader
{
	[default_interface]
	runtimeclass MainWindowViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		MainWindowViewModel(); 
		
		void LoadData(); 
		void SaveData();
		void OnChaptersChanged(Object obj); 
		Windows.Foundation.IAsyncAction ShowUsages(); 

		Int32 ChapterIndex; 
		Int32 LineHeightIndex;
		Int32 FontSizeIndex;
		Int32 FontFamilyIndex;
		Int32 ThemeIndex; 
		Int32 FontWeightIndex; 

		Int32 WindowPositionX; 
		Int32 WindowPositionY; 
		Int32 WindowSizeW; 
		Int32 WindowSizeH; 
		Double ReaderVerticalOffset; 

		Xuanwen.Novel.NovelBook CurrentBook; 
		Xuanwen.Novel.Chapter CurrentChapter{ get; }; 

		Double LineHeight{ get; }; 
		Double FontSize{ get; }; 
		Microsoft.UI.Xaml.Media.FontFamily FontFamily{ get; }; 
		AppTheme AppTheme{ get; }; 
		Windows.UI.Text.FontWeight FontWeight{ get; }; 

		Windows.Foundation.Collections.IVector<AppFont> FontItems { get; };
		Windows.Foundation.Collections.IVector<DoubleItem> FontSizeItems{ get; }; 
		Windows.Foundation.Collections.IVector<DoubleItem> LineHeightItems{ get; };
		Windows.Foundation.Collections.IVector<AppTheme> ThemeItems{ get; };
		Windows.Foundation.Collections.IVector<FontWeightItem> FontWeightItems{ get; };
		
	}
}
