namespace Win2dTextReader
{
	[default_interface]
	runtimeclass ReaderTheme
	{
		ReaderTheme(Int32 index, String displayName); 
		Microsoft.UI.Xaml.Media.Brush FontColor{ get; };
		Microsoft.UI.Xaml.Media.Brush Background{ get; }; 
		String DisplayName{ get; }; 
	}
}
