import "MainWindowViewModel.idl"; 

namespace Win2dTextReader
{
    [default_interface]
    runtimeclass Settings : Microsoft.UI.Xaml.Controls.UserControl
    {
        Settings(MainWindowViewModel viewModel);
        
        MainWindowViewModel ViewModel{ get; };
    }
}
